name: Bazel Test
on: [push]
jobs:
  Bazel-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dead snake python
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa &&
          sudo apt-get -yq update &&
          sudo apt-get -yq install python3.6-minimal python3.6-dev libpython3.6-minimal
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build
        run: cd ${{ github.workspace }} && bazelisk build --config=small-tests //...
      - name: Test
        run: cd ${{ github.workspace }} && bazelisk test -j 1 --config=small-tests //...
